// Auto-generated by sim/train.py - do not edit by hand.
// 4 distance states x 3 actions. Loaded into the ESP32 as the
// starting Q-table; the robot keeps learning on top of this.
#ifndef QTABLE_H
#define QTABLE_H

#define Q_STATES  4
#define Q_ACTIONS 3

const float Q_INIT[Q_STATES][Q_ACTIONS] = {
  { 3.2412f, 16.0667f, 15.0481f },   // Danger
  { 6.1332f, 15.1756f, 13.3114f },   // Close
  { 15.6090f, 14.5928f, 12.7760f },   // Comfortable
  { 18.1691f, 15.3997f, 17.2904f },   // Clear
};

#endif // QTABLE_H
