#!/usr/bin/env python3
"""
Q-learning trainer for the autonomous cat robot.

Trains a 4 (distance states) x 3 (actions) table in a tiny simulated world that
mimics the HC-SR04 distance dynamics, prints the converged policy with a plain
-English behavior reading, and exports the table as `qtable.h` for the ESP32.

Usage:
    python3 train.py                  # defaults (danger penalty -6)
    python3 train.py --danger -10     # try a harsher danger penalty
    python3 train.py --steps 60000 --seed 1
"""

import argparse
import random

# ---- States (from ultrasonic distance, cm) -------------------------------
# 0 Danger      <6
# 1 Close       6-18
# 2 Comfortable 18-40
# 3 Clear       >40
DANGER, CLOSE, COMFORTABLE, CLEAR = 0, 1, 2, 3
STATE_NAMES = ["Danger", "Close", "Comfortable", "Clear"]

# ---- Actions -------------------------------------------------------------
FORWARD, TURN, REVERSE = 0, 1, 2
ACTION_NAMES = ["Forward", "Turn", "Reverse"]

# ---- World model thresholds ----------------------------------------------
D_MIN, D_MAX = 2.0, 80.0
T_DANGER, T_CLOSE, T_COMF = 6.0, 18.0, 40.0
FORWARD_STEP = 9.0   # cm closer per forward tick
REVERSE_STEP = 9.0   # cm farther per reverse tick
MOVE_NOISE = 2.0     # +/- cm sensor/motion noise


def state_from_distance(d):
    if d < T_DANGER:
        return DANGER
    if d < T_CLOSE:
        return CLOSE
    if d < T_COMF:
        return COMFORTABLE
    return CLEAR


def world_step(d, action):
    """Return the new distance after taking `action` from distance `d`."""
    noise = random.uniform(-MOVE_NOISE, MOVE_NOISE)
    if action == FORWARD:
        d = d - FORWARD_STEP + noise          # approach the thing ahead
    elif action == REVERSE:
        d = d + REVERSE_STEP + noise          # back away
    else:  # TURN -> now facing a new direction, fresh distance
        d = random.uniform(10.0, 70.0)
    return max(D_MIN, min(D_MAX, d))


def reward(action, new_state, danger_penalty, danger_forward_extra):
    """Reward depends on the state the action LANDED us in (+ the action)."""
    if new_state == DANGER:
        r = danger_penalty
        if action == FORWARD:
            r += danger_forward_extra          # drove straight into it: worse
        return r
    if new_state == CLOSE:
        return -1.0 if action == FORWARD else +1.0     # reward backing off
    if new_state == COMFORTABLE:
        # the "following" sweet spot and the value PEAK: strongly reward inching
        # forward to hold the gap, and discourage backing out of it.
        if action == FORWARD:
            return +5.0
        if action == REVERSE:
            return -3.0                                # backing out of the sweet
                                                       # spot toward open space
                                                       # must genuinely cost
        return 0.0                                     # Turn: neutral
    # CLEAR: pleasant enough to roam toward, but deliberately LESS valuable than
    # Comfortable so the cat prefers being near you over fleeing to open space.
    return +1.0 if action == FORWARD else 0.0


def train(steps, alpha, gamma, eps_start, eps_end,
          danger_penalty, danger_forward_extra):
    Q = [[0.0] * 3 for _ in range(4)]
    d = random.uniform(D_MIN, D_MAX)
    s = state_from_distance(d)
    for i in range(steps):
        eps = eps_start + (eps_end - eps_start) * (i / steps)  # linear decay
        if random.random() < eps:
            a = random.randint(0, 2)
        else:
            a = max(range(3), key=lambda x: Q[s][x])
        d2 = world_step(d, a)
        s2 = state_from_distance(d2)
        r = reward(a, s2, danger_penalty, danger_forward_extra)
        # Bellman update
        Q[s][a] += alpha * (r + gamma * max(Q[s2]) - Q[s][a])
        d, s = d2, s2
    return Q


def print_policy(Q):
    print(f"\n{'State':<14}{'Forward':>9}{'Turn':>9}{'Reverse':>9}   -> chooses")
    print("-" * 60)
    behavior = {
        DANGER:      "backs off / turns away from an obstacle at its face",
        CLOSE:       "cautious — eases off when something is 6-18cm",
        COMFORTABLE: "follows / holds the sweet spot (18-40cm)",
        CLEAR:       "roams forward freely in open space",
    }
    for s in range(4):
        best = max(range(3), key=lambda x: Q[s][x])
        row = "".join(f"{Q[s][a]:>9.2f}" for a in range(3))
        print(f"{STATE_NAMES[s]:<14}{row}   -> {ACTION_NAMES[best]}")
    print()
    for s in range(4):
        best = max(range(3), key=lambda x: Q[s][x])
        print(f"  {STATE_NAMES[s]:<12}: {ACTION_NAMES[best]:<8} -> {behavior[s]}")


def export_header(Q, path):
    lines = [
        "// Auto-generated by sim/train.py - do not edit by hand.",
        "// 4 distance states x 3 actions. Loaded into the ESP32 as the",
        "// starting Q-table; the robot keeps learning on top of this.",
        "#ifndef QTABLE_H",
        "#define QTABLE_H",
        "",
        "#define Q_STATES  4",
        "#define Q_ACTIONS 3",
        "",
        "const float Q_INIT[Q_STATES][Q_ACTIONS] = {",
    ]
    for s in range(4):
        vals = ", ".join(f"{Q[s][a]:.4f}f" for a in range(3))
        lines.append(f"  {{ {vals} }},   // {STATE_NAMES[s]}")
    lines += ["};", "", "#endif // QTABLE_H", ""]
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"\nExported -> {path}")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--steps", type=int, default=40000)
    p.add_argument("--alpha", type=float, default=0.2)
    p.add_argument("--gamma", type=float, default=0.9)
    p.add_argument("--eps-start", type=float, default=0.30)
    p.add_argument("--eps-end", type=float, default=0.05)
    p.add_argument("--danger", type=float, default=-6.0,
                   help="reward for landing in the Danger state")
    p.add_argument("--danger-forward-extra", type=float, default=-5.0,
                   help="extra penalty if we drove FORWARD into danger")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--out", default="qtable.h")
    p.add_argument("--no-export", action="store_true")
    args = p.parse_args()

    random.seed(args.seed)
    Q = train(args.steps, args.alpha, args.gamma, args.eps_start, args.eps_end,
              args.danger, args.danger_forward_extra)
    print(f"Trained {args.steps} steps | danger penalty = {args.danger} "
          f"(+{args.danger_forward_extra} extra if forward)")
    print_policy(Q)
    if not args.no_export:
        export_header(Q, args.out)


if __name__ == "__main__":
    main()
